### ISSUE TITLE
A couple questions

### ISSUE THREAD

**Issue by travisw** [rupok/flexia#17]
Hi there,
I have a couple of questions.

1. It looks like it's only possible to set the responsive fullscreen image on the blog page. Is it possible to use this on a different page? One that might not show blog posts?

2. Is there anything built in to allow the fullscreen image to cycle through multiple images, acting as a feature content slider?

Thanks!

**Comment by bluesbruno** [comment]
I too am interested in these two topics

**Comment by rupok** [comment]
Hello guys,

Thanks for chime in! 

#1. It's possible with any page builder especially with Elementor. Flexia is built to work with any page builder out there. So it would be easy to achieve this. See https://wpdeveloper.net for example. I built this with Flexia and Elementor.

#2. We will add slider extension along with lots of other cool extensions. Just wait few more days.

Cheers!

**Comment by bluesbruno** [comment]
Hello Rupok,
I can't find the fullscreen image option in Elementor that would allow me to have a full screen image header the way the blog page does. How exactly do you achieve this?

**Comment by rupok** [comment]
Hi @bluesbruno 

Let's select the "Section" and you will see the option "Height" in left panel. You can set this to "Fit to Screen". That will do the job.

Thanks!
