### ISSUE TITLE
Background style and personalized image

### ISSUE THREAD

**Issue by ckone8703** [rupok/flexia#19]
I'm using Theme flexia, and I face issues when I use a background picture for the pages + White background for the text : the white background does not seem to be recognized and the text is not lisible on the picture.
website: http://airtech-mrs.fr/
I had the same issue yesterday on another webiste using the same template but it got solved on its own...http://www.airt-tech.fr/ 
But seems that today, on the new webiste it does not work with the same settings.
Version wordpress:  4.9.1–fr_FR

thanks for your quick help!!
carine

**Comment by rupok** [comment]
Hello @ckone8703 ckone870

I got your message and I'll reply there. As it's not an issue rather specific to your setup, I am closing this here. I'll get back to you in email.

Thanks!
