### ISSUE TITLE
Header Picture does not work on IE11

### ISSUE THREAD

**Issue by brou1973** [rupok/flexia#20]
Dear Support Team, 

when viewing your Flexia layout with IE11, the Header Picture is limited in height and the arrow down is not functional.
I think it´s caused by the error thrown in line 190 (see screenshot).
![error](https://user-images.githubusercontent.com/35425360/34917007-7dc27d40-f938-11e7-8acc-f1067f796114.jpg)

Any help would highly be appreciated.

**Comment by rupok** [comment]
Hi @brou1973, 

We are using default WordPress header image feature. So it should work fine on IE11. I'll check and fix if something on our code.

Thanks!
