### ISSUE TITLE
BuddyPress integration 

### ISSUE THREAD

**Issue by M4LWare666** [rupok/flexia#22]
WordPress version: 4.9.6
PHP: 7.1.12
MySQL: 5.6

Sorry, to raise an issue but I have a question in regards to integration and use with flexia theme.

Is flexia capable of becoming BuddyPress incorporated for a more customize BuddyPress setting as is ?

I have been hesitant to ask this question and raise an issue, but I have inherited a project that uses this theme and relies on heavy use of the Elementor page-builder and utilizes the customizer section quite a bit. I am worried about the javascript and php everywhere in the admin system set-up also.
 
Obviously the WordPress site overall has not been dealt with programmatically and also is using lots of 3rd party plugins and addons additionally to the flexia theme and plugin-core framework. 

Would you say its "safe" to develop on this theme additional or will it break completely? I do not really want to start hacking on the theme because of the reliance on the framework and plugin-core.
Which also makes a child theme solution a little more difficult.

Any thoughts or experience integrating BuddyPress would be much appreciated!

**Comment by rupok** [comment]
Hi @hightide2020 

Hope you are doing well. Flexia is very standard WordPress theme and we made "Flexia Core" as separate plugin just to make sure we can always maintain the compatibility of Flexia. That being said, Flexia should support any standard WordPress plugin without any issue and we are working to ensure more seamless integration with popular plugins like BuddyPress. And we are distributing the theme through wp.org so you can rely on the security and compatibility. Also as it's on Github, you can always raise issues and even contribute.
Let me know if you have any other specific question.
Cheers!

**Comment by hightide2020** [comment]
@rupok thanks for the quick response just wanted to make sure before I went forth and forced the BuddyPress integrations. 

I will let you know how it goes,

Cheers!
