### ISSUE TITLE
Child theme stylesheet priority

### ISSUE THREAD

**Issue by Huluti** [rupok/flexia#42]
HI! I've an issue with the theme which I've managed to fix by myself but it could help you to fix this problem.

For my CSS rules in my custom stylesheet of my child theme to be applied I've to dequeue the flexia CSS to readd it after with the good dependence:

```php 
function child_enqueue_styles() {
    $parent_style = 'flexia-theme-style';
    wp_dequeue_style($parent_style);
    wp_enqueue_style($parent_style, get_template_directory_uri() . '/framework/assets/site/css/style.css');
    wp_enqueue_style('child-style', get_stylesheet_directory_uri() . '/style.css', array( $parent_style ), FLEXIA_CHILD_INFLUXE_VERSION, 'all');
}
add_action( 'wp_enqueue_scripts', 'child_enqueue_styles' );
```

**Comment by jamilbd07** [comment]
Hi @Huluti ,
Thanks for your advise. But can you please share the problem you have faced with our child theme?

**Comment by Huluti** [comment]
Hi @jamilbd07. In fact, with the provided child theme each CSS rule that I wanted to applied must be provided with `!important`.

It's because the flexia stylesheet was loaded after the child theme.
With my code it displace the flexia parent style before the call to the child theme stylesheet:

Before:
```html
<link rel='stylesheet' id='child-style-css'  href='https://influxe.fr/wp-content/themes/influxe/style.css?ver=1.0.0' type='text/css' media='all' />
<link rel='stylesheet' id='flexia-theme-style-css'  href='https://influxe.fr/wp-content/themes/flexia/framework/assets/site/css/style.css?ver=5.5.3' type='text/css' media='all' />
```

After:
```html
<link rel='stylesheet' id='flexia-theme-style-css'  href='https://influxe.fr/wp-content/themes/flexia/framework/assets/site/css/style.css?ver=5.5.3' type='text/css' media='all' />
<link rel='stylesheet' id='child-style-css'  href='https://influxe.fr/wp-content/themes/influxe/style.css?ver=1.0.0' type='text/css' media='all' />
```

It's the first time with a theme that I must do this trick (with wp_dequeue_style and wp_enqueue_style) to have my rules correctly applied.

**Comment by jamilbd07** [comment]
@Huluti , thanks for finding this out. You are awesome!

**Comment by Huluti** [comment]
@jamilbd07 So you've found the cause of this problem?

**Comment by jamilbd07** [comment]
@Huluti Actually this issue was never issued before that's why we didn't figure this out. But thank you for finding this issue and solve the issue for us.
