### ISSUE TITLE
Please activate your license key to enable updates for Flexia Pro.

### ISSUE THREAD

**Issue by git-wpmudev** [rupok/flexia#43]
Hello Support-Team,

its most annozing and irritating that the 'Please activate your license key to enable updates for Flexia Pro' message turns permanently on each site up.

Indeed I activated my purchased PRO version ... therefore it would be wonderful if you help me, how to eliminate that message.
Thank you.

**Comment by khan-rafin-ahmed** [comment]
Hi @git-wpmudev,

That's actually strange. Well, make sure you have installed & activated the Flexia Core plugin on your website as well. 

And, if you have done that and still facing the issue, please contact our support here: https://wpdeveloper.net/support/new-ticket/

Thank you!
