### ISSUE TITLE
Translate Menu user connection Sign In and Log Out

### ISSUE THREAD

**Issue by Richard76000** [rupok/flexia#44]
Hello, I would like to modify the user connection menu in French: Sign In and Log out
I tried the Loco translate plugin, Say What nothing to do ... Can you help me please ?

Thanks a lot

**Comment by fencermonir** [comment]
Hi @Richard76000 
We got your concern, we are looking into it. Hope we will get back to you soon.

**Comment by khan-rafin-ahmed** [comment]
Hi @Richard76000,

You can easily resolve this by updating your **.pot** file. You can download the updated .pot file from here: https://d.pr/f/yTodjA

Afterward, replace the old .pot file with the new one I shared from this following file location (which you can access through your cPanel or FTP): _**wp-content/themes/flexia/languages/flexia.pot**_

I hope this will resolve the issue of yours. Let me know how it goes. Thank you!

**Comment by Richard76000** [comment]
Thanks a lot !
